/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tablahash;

/**
 *
 * @author Daniel
 */
public class Menu_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Menu_Principal
     */
    public Menu_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jLabel_ID = new javax.swing.JLabel();
        jTextField_ID = new javax.swing.JTextField();
        jLabel_Nombre = new javax.swing.JLabel();
        jTextField_Nombre = new javax.swing.JTextField();
        jLabel_Año = new javax.swing.JLabel();
        jTextField_Año = new javax.swing.JTextField();
        jLabel_Genero = new javax.swing.JLabel();
        jTextField_Genero = new javax.swing.JTextField();
        Insertar = new javax.swing.JButton();
        jLabel_InsertarDatos = new javax.swing.JLabel();
        Fondo2 = new javax.swing.JLabel();
        jLabel_Iniciar = new javax.swing.JLabel();
        Iniciar = new javax.swing.JButton();
        jLabel_Reiniciar = new javax.swing.JLabel();
        Reiniciar = new javax.swing.JButton();
        jLabel_Insertar = new javax.swing.JLabel();
        InsertarPelicula = new javax.swing.JButton();
        jLabel_Buscar = new javax.swing.JLabel();
        Buscar = new javax.swing.JButton();
        jLabel_Eliminar = new javax.swing.JLabel();
        Eliminar = new javax.swing.JButton();
        jLabel_Mostrar = new javax.swing.JLabel();
        MostrarTabla = new javax.swing.JButton();
        jLabel_Estadistica = new javax.swing.JLabel();
        Estadistica = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        area_texto = new javax.swing.JTextArea();
        jTextField_TamanoTabla = new javax.swing.JTextField();
        jLabel_TamanoTabla = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        jDialog1.getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_ID.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_ID.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ID.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_ID.setText("ID:");
        jDialog1.getContentPane().add(jLabel_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 20, 20));
        jDialog1.getContentPane().add(jTextField_ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 120, -1));

        jLabel_Nombre.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Nombre.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Nombre.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Nombre.setText("Nombre: ");
        jDialog1.getContentPane().add(jLabel_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 50, -1));
        jDialog1.getContentPane().add(jTextField_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 120, -1));

        jLabel_Año.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Año.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Año.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Año.setText("Año:");
        jDialog1.getContentPane().add(jLabel_Año, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 30, -1));
        jDialog1.getContentPane().add(jTextField_Año, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 120, -1));

        jLabel_Genero.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Genero.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Genero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Genero.setText("Genero:");
        jDialog1.getContentPane().add(jLabel_Genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        jTextField_Genero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_GeneroActionPerformed(evt);
            }
        });
        jDialog1.getContentPane().add(jTextField_Genero, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 120, -1));

        Insertar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/video-editor.png"))); // NOI18N
        Insertar.setBorderPainted(false);
        Insertar.setContentAreaFilled(false);
        jDialog1.getContentPane().add(Insertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 35, -1));

        jLabel_InsertarDatos.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_InsertarDatos.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_InsertarDatos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_InsertarDatos.setText("Insertar");
        jDialog1.getContentPane().add(jLabel_InsertarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, -1, -1));

        Fondo2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fondo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo2.jpeg"))); // NOI18N
        jDialog1.getContentPane().add(Fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 270, 290));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Iniciar.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Iniciar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Iniciar.setText("Iniciar");
        getContentPane().add(jLabel_Iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 40, 20));

        Iniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/encender.png"))); // NOI18N
        Iniciar.setBorderPainted(false);
        Iniciar.setContentAreaFilled(false);
        getContentPane().add(Iniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 40, 40));

        jLabel_Reiniciar.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Reiniciar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Reiniciar.setText("Reiniciar");
        getContentPane().add(jLabel_Reiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        Reiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/reiniciar.png"))); // NOI18N
        Reiniciar.setBorderPainted(false);
        Reiniciar.setContentAreaFilled(false);
        getContentPane().add(Reiniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 40, 40));

        jLabel_Insertar.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Insertar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Insertar.setText("Inserta Pelicula");
        getContentPane().add(jLabel_Insertar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        InsertarPelicula.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/video-editor.png"))); // NOI18N
        InsertarPelicula.setBorderPainted(false);
        InsertarPelicula.setContentAreaFilled(false);
        getContentPane().add(InsertarPelicula, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 30, 40));

        jLabel_Buscar.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Buscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Buscar.setText("Buscar Pelicula");
        getContentPane().add(jLabel_Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        Buscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/movie-folder.png"))); // NOI18N
        Buscar.setBorderPainted(false);
        Buscar.setContentAreaFilled(false);
        Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarActionPerformed(evt);
            }
        });
        getContentPane().add(Buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 40, 40));

        jLabel_Eliminar.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Eliminar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Eliminar.setText("Eliminar Pelicula");
        getContentPane().add(jLabel_Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        Eliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/borrar.png"))); // NOI18N
        Eliminar.setBorderPainted(false);
        Eliminar.setContentAreaFilled(false);
        getContentPane().add(Eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 40, 40));

        jLabel_Mostrar.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Mostrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Mostrar.setText("Mostrar Tabla");
        getContentPane().add(jLabel_Mostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        MostrarTabla.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/proyector.png"))); // NOI18N
        MostrarTabla.setBorderPainted(false);
        MostrarTabla.setContentAreaFilled(false);
        getContentPane().add(MostrarTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 410, 40, -1));

        jLabel_Estadistica.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Estadistica.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Estadistica.setText("Estadistica");
        getContentPane().add(jLabel_Estadistica, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        Estadistica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/diagrama.png"))); // NOI18N
        Estadistica.setBorderPainted(false);
        Estadistica.setContentAreaFilled(false);
        getContentPane().add(Estadistica, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 480, 40, 40));

        area_texto.setColumns(20);
        area_texto.setRows(5);
        jScrollPane1.setViewportView(area_texto);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 280, 520));
        getContentPane().add(jTextField_TamanoTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 70, -1));

        jLabel_TamanoTabla.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_TamanoTabla.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_TamanoTabla.setText("Ingrese el tamaño de la tabla:");
        getContentPane().add(jLabel_TamanoTabla, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, -1));

        Fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo2.jpeg"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BuscarActionPerformed

    private void jTextField_GeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_GeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_GeneroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Buscar;
    private javax.swing.JButton Eliminar;
    private javax.swing.JButton Estadistica;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Fondo2;
    private javax.swing.JButton Iniciar;
    private javax.swing.JButton Insertar;
    private javax.swing.JButton InsertarPelicula;
    private javax.swing.JButton MostrarTabla;
    private javax.swing.JButton Reiniciar;
    private javax.swing.JTextArea area_texto;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel_Año;
    private javax.swing.JLabel jLabel_Buscar;
    private javax.swing.JLabel jLabel_Eliminar;
    private javax.swing.JLabel jLabel_Estadistica;
    private javax.swing.JLabel jLabel_Genero;
    private javax.swing.JLabel jLabel_ID;
    private javax.swing.JLabel jLabel_Iniciar;
    private javax.swing.JLabel jLabel_Insertar;
    private javax.swing.JLabel jLabel_InsertarDatos;
    private javax.swing.JLabel jLabel_Mostrar;
    private javax.swing.JLabel jLabel_Nombre;
    private javax.swing.JLabel jLabel_Reiniciar;
    private javax.swing.JLabel jLabel_TamanoTabla;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField_Año;
    private javax.swing.JTextField jTextField_Genero;
    private javax.swing.JTextField jTextField_ID;
    private javax.swing.JTextField jTextField_Nombre;
    private javax.swing.JTextField jTextField_TamanoTabla;
    // End of variables declaration//GEN-END:variables
}

